<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
function fail(string $message, int $status = 400, array $extra = []): never { http_response_code($status); echo json_encode(array_merge(['error'=>$message], $extra), JSON_UNESCAPED_UNICODE); exit; }
function parse_payload(): array { $raw=file_get_contents('php://input'); if($raw===false||trim($raw)==='') return []; try { $payload=json_decode($raw,true,flags:JSON_THROW_ON_ERROR); return is_array($payload)?$payload:[]; } catch(Throwable $e){ fail('JSON invalide: '.$e->getMessage(),400);} }
function as_string(array $src,string $key,bool $required=true): ?string { $value=$src[$key]??null; if($value===null||$value===''){ if($required) fail("champ requis: {$key}"); return null;} return (string)$value; }
function repo_root(): string { return dirname(__DIR__); }
function default_db_path(): string { return repo_root().'/jarvis/database/db.db'; }
function tools_root(): string { return repo_root().'/jarvis/toolbox/tools'; }
function connect_db(?string $requestedPath): PDO { $dbPath=$requestedPath?: (getenv('JARVIS_INFRA_DB')?:default_db_path()); $dir=dirname($dbPath); if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir)) fail('impossible de créer le dossier de la DB',500); $pdo=new PDO('sqlite:'.$dbPath); $pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION); $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC); ensure_infra_schema($pdo); return $pdo; }
function ensure_infra_schema(PDO $pdo): void {
$pdo->exec("CREATE TABLE IF NOT EXISTS sensitive_values (namespace TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),PRIMARY KEY(namespace, key))");
$pdo->exec("CREATE TABLE IF NOT EXISTS npm_instances (name TEXT PRIMARY KEY,base_url TEXT NOT NULL,login TEXT NOT NULL,password TEXT,password_secret_key TEXT,CHECK ((password IS NOT NULL AND password_secret_key IS NULL) OR (password IS NULL AND password_secret_key IS NOT NULL)))");
$pdo->exec("CREATE TABLE IF NOT EXISTS npm_services (domain TEXT PRIMARY KEY,instance_name TEXT NOT NULL,forward_host TEXT NOT NULL,forward_port INTEGER NOT NULL,scheme TEXT NOT NULL DEFAULT 'http',FOREIGN KEY(instance_name) REFERENCES npm_instances(name))");
$pdo->exec("CREATE TABLE IF NOT EXISTS proxmox_targets (name TEXT PRIMARY KEY,ip TEXT NOT NULL,api_path TEXT NOT NULL DEFAULT '/api2/json',login TEXT NOT NULL,password TEXT,password_secret_key TEXT,node TEXT NOT NULL,CHECK ((password IS NOT NULL AND password_secret_key IS NULL) OR (password IS NULL AND password_secret_key IS NOT NULL)))");
$pdo->exec("CREATE TABLE IF NOT EXISTS ct_services (name TEXT PRIMARY KEY,target_name TEXT NOT NULL,ctid INTEGER NOT NULL,path TEXT NOT NULL,FOREIGN KEY(target_name) REFERENCES proxmox_targets(name))");
}
function db_contract(): array { return ['db_path_resolution'=>['payload.db_path','env.JARVIS_INFRA_DB',default_db_path()],'tables'=>[
['name'=>'sensitive_values','used_by'=>['config-web','npm_service','proxmox_ct'],'columns'=>['namespace','key','value','updated_at']],
['name'=>'npm_instances','used_by'=>['npm_service'],'columns'=>['name','base_url','login','password','password_secret_key']],
['name'=>'npm_services','used_by'=>['npm_service'],'columns'=>['domain','instance_name','forward_host','forward_port','scheme']],
['name'=>'proxmox_targets','used_by'=>['proxmox_ct'],'columns'=>['name','ip','api_path','login','password','password_secret_key','node']],
['name'=>'ct_services','used_by'=>['proxmox_ct'],'columns'=>['name','target_name','ctid','path']],
['name'=>'devlab_runs','used_by'=>['devlab_backend'],'columns'=>['run_id','tool_name','mode','status','started_at','ended_at','duration_ms','summary','payload_json','output_json','trace_json','diag_json'],'note'=>'Créée automatiquement par devlab_backend.'],],
'required_sensitive_keys'=>['runtime'=>['TOOLBOX_RUNNER_URL'],'npm_service'=>['NPM_URL','NPM_IDENTITY','NPM_SECRET'],'proxmox'=>['PROXMOX_PASSWORD']]]; }
function list_tables(PDO $pdo): array { return $pdo->query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")->fetchAll(); }
function table_exists(PDO $pdo,string $table): bool { $stmt=$pdo->prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=:name LIMIT 1"); $stmt->execute([':name'=>$table]); return (bool)$stmt->fetchColumn(); }
function get_table_columns(PDO $pdo,string $table): array { if(!preg_match('/^[a-zA-Z0-9_]+$/',$table)) fail('nom de table invalide'); $rows=$pdo->query('PRAGMA table_info('.$table.')')->fetchAll(); return array_values(array_map(static fn(array $row)=>(string)$row['name'],$rows)); }
function get_table_rows(PDO $pdo,string $table,int $limit=100,int $offset=0): array { $columns=get_table_columns($pdo,$table); $stmt=$pdo->prepare('SELECT * FROM '.$table.' LIMIT :limit OFFSET :offset'); $stmt->bindValue(':limit',$limit,PDO::PARAM_INT); $stmt->bindValue(':offset',$offset,PDO::PARAM_INT); $stmt->execute(); return ['columns'=>$columns,'rows'=>$stmt->fetchAll()]; }
function list_namespaces(PDO $pdo): array { if(!table_exists($pdo,'sensitive_values')) return []; $stmt=$pdo->query("SELECT DISTINCT namespace FROM sensitive_values ORDER BY namespace"); return array_values(array_map(static fn(array $row)=>(string)$row['namespace'],$stmt->fetchAll())); }
function list_sensitive(PDO $pdo,string $namespace): array { $stmt=$pdo->prepare("SELECT namespace,key,value,updated_at FROM sensitive_values WHERE namespace=:namespace ORDER BY key"); $stmt->execute([':namespace'=>$namespace]); return $stmt->fetchAll(); }
function upsert_sensitive(PDO $pdo,string $namespace,string $key,string $value): void { $stmt=$pdo->prepare("INSERT INTO sensitive_values(namespace,key,value) VALUES(:namespace,:key,:value) ON CONFLICT(namespace,key) DO UPDATE SET value=excluded.value,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ', 'now')"); $stmt->execute([':namespace'=>$namespace,':key'=>$key,':value'=>$value]); }
function delete_sensitive(PDO $pdo,string $namespace,string $key): bool { $stmt=$pdo->prepare("DELETE FROM sensitive_values WHERE namespace=:namespace AND key=:key"); $stmt->execute([':namespace'=>$namespace,':key'=>$key]); return $stmt->rowCount()>0; }
function schema_health(PDO $pdo): array { $items=[]; foreach(db_contract()['tables'] as $table){ $name=(string)$table['name']; $present=table_exists($pdo,$name); $actual=$present?get_table_columns($pdo,$name):[]; $expected=$table['columns']??[]; $missing=array_values(array_diff($expected,$actual)); $extra=array_values(array_diff($actual,$expected)); $items[]=['table'=>$name,'present'=>$present,'expected_columns'=>$expected,'actual_columns'=>$actual,'missing_columns'=>$missing,'extra_columns'=>$extra,'used_by'=>$table['used_by']??[],'ok'=>$present&&count($missing)===0,'note'=>$table['note']??null]; } return $items; }
function normalize_tool_version(array $manifest): string { $version=(string)($manifest['version']??$manifest['tool_version']??'v0'); return $version!==''?$version:'v0'; }
function discover_manifest_paths(string $root): array { if(!is_dir($root)) return []; $paths=[]; $iter=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS)); foreach($iter as $fileInfo){ if(!$fileInfo instanceof SplFileInfo||!$fileInfo->isFile()) continue; if($fileInfo->getFilename()!=='manifest.json') continue; $paths[]=$fileInfo->getPathname(); } sort($paths); return $paths; }
function discover_python_paths(string $root): array { if(!is_dir($root)) return []; $paths=[]; $iter=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS)); foreach($iter as $fileInfo){ if(!$fileInfo instanceof SplFileInfo||!$fileInfo->isFile()) continue; if($fileInfo->getExtension()!=='py') continue; $paths[]=$fileInfo->getPathname(); } sort($paths); return $paths; }
function sample_from_schema(array $schema): mixed { if(array_key_exists('default',$schema)) return $schema['default']; if(isset($schema['enum'])&&is_array($schema['enum'])&&count($schema['enum'])>0) return $schema['enum'][0]; $type=$schema['type']??null; if($type==='object'){ $out=[]; $properties=$schema['properties']??[]; if(!is_array($properties)) return new stdClass(); foreach($properties as $name=>$childSchema){ if(!is_string($name)||!is_array($childSchema)) continue; $out[$name]=sample_from_schema($childSchema); } return $out; } if($type==='array') return []; if($type==='integer'||$type==='number') return 0; if($type==='boolean') return false; if($type==='string') return ''; return null; }
function list_python_tools(): array { $tools=[]; $realRoot=realpath(tools_root())?:''; foreach(discover_manifest_paths(tools_root()) as $manifestPath){ $manifest=json_decode(file_get_contents($manifestPath)?:'{}',true); if(!is_array($manifest)) continue; $entrypoint=(string)($manifest['entrypoint']??'tool.py'); if(pathinfo($entrypoint,PATHINFO_EXTENSION)!=='py') continue; $toolDir=dirname($manifestPath); $toolCodePath=realpath($toolDir.DIRECTORY_SEPARATOR.$entrypoint); if(!$toolCodePath||($realRoot!==''&&!str_starts_with($toolCodePath,$realRoot))) continue; $sampleInput=[]; if(isset($manifest['input_schema'])&&is_array($manifest['input_schema'])){ $sample=sample_from_schema($manifest['input_schema']); if(is_array($sample)) $sampleInput=$sample; } $tools[]=['name'=>(string)($manifest['name']??basename(dirname($manifestPath))),'version'=>normalize_tool_version($manifest),'description'=>(string)($manifest['description']??''),'entrypoint'=>$entrypoint,'manifest_path'=>str_replace(repo_root().'/', '', $manifestPath),'code_path'=>str_replace(repo_root().'/', '', $toolCodePath),'sample_input'=>$sampleInput,'required_fields'=>$manifest['input_schema']['required']??[],'input_schema'=>$manifest['input_schema']??new stdClass()]; } return $tools; }
function list_python_files(): array { $files=[]; $realRoot=realpath(tools_root()); if($realRoot===false) return []; foreach(discover_python_paths(tools_root()) as $path){ $realPath=realpath($path); if($realPath===false||!str_starts_with($realPath,$realRoot)) continue; $relative=str_replace(repo_root().'/', '', $realPath); $toolDir=dirname($relative); $manifestPath=$toolDir.'/manifest.json'; $files[]=['path'=>$relative,'tool_dir'=>$toolDir,'filename'=>basename($relative),'manifest_exists'=>is_file(repo_root().'/'.$manifestPath),'size'=>filesize($realPath)?:0,'mtime'=>gmdate('c', filemtime($realPath) ?: time())]; } return $files; }
function browse_paths(?string $path): array { $target=($path!==null&&trim($path)!=='')?trim($path):dirname(default_db_path()); if(!is_dir($target)) fail('le chemin doit être un dossier'); $entries=scandir($target); if($entries===false) fail('impossible de lire le dossier',500); $items=[]; foreach($entries as $entry){ if($entry==='.'||$entry==='..') continue; $full=rtrim($target,DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.$entry; $isDir=is_dir($full); if(!$isDir&&!preg_match('/\.(db|sqlite|sqlite3)$/i',$entry)) continue; $items[]=['name'=>$entry,'path'=>$full,'type'=>$isDir?'dir':'file','writable'=>is_writable($full),'size'=>$isDir?null:(filesize($full)?:0)]; } usort($items, static function(array $a,array $b): int { if($a['type']!==$b['type']) return $a['type']==='dir'?-1:1; return strcmp((string)$a['name'], (string)$b['name']);}); $parent=dirname($target); return ['current_path'=>$target,'parent_path'=>$parent!==$target?$parent:null,'items'=>$items]; }
function download_db_file(string $path): never { if(!is_file($path)) fail('fichier DB introuvable',404); header_remove('Content-Type'); header('Content-Type: application/octet-stream'); header('Content-Disposition: attachment; filename="'.basename($path).'"'); readfile($path); exit; }

$payload=parse_payload(); $action=isset($payload['action'])?(string)$payload['action']:''; $dbPath=isset($payload['db_path'])?(string)$payload['db_path']:null; $pdo=null;
$dbActions=['healthcheck','db_contract','db_schema_status','db_init_schema','list_namespaces','list_sensitive','upsert_sensitive','delete_sensitive','list_tables','get_table_rows','list_npm_instances','save_npm_instance','delete_npm_instance','list_npm_services','save_npm_service','delete_npm_service','list_proxmox_targets','save_proxmox_target','delete_proxmox_target','list_ct_services','save_ct_service','delete_ct_service'];
if(in_array($action,$dbActions,true)) $pdo=connect_db($dbPath);
error_log('[config-web/api] action='.$action.' db='.($dbPath?:''));
switch($action){
case 'healthcheck': $tools=list_python_tools(); $files=list_python_files(); echo json_encode(['ok'=>true,'db_path'=>$dbPath?: (getenv('JARVIS_INFRA_DB')?:default_db_path()),'repo_root'=>repo_root(),'tools_root'=>tools_root(),'tools_root_exists'=>is_dir(tools_root()),'tools_count'=>count($tools),'python_files_count'=>count($files),'tools_preview'=>array_slice($tools,0,20),'python_files_preview'=>array_slice($files,0,20),'tables'=>list_tables($pdo),'namespaces'=>list_namespaces($pdo),'schema_health'=>schema_health($pdo)], JSON_UNESCAPED_UNICODE); break;
case 'db_contract': echo json_encode(['ok'=>true,'contract'=>db_contract()], JSON_UNESCAPED_UNICODE); break;
case 'db_schema_status': echo json_encode(['ok'=>true,'items'=>schema_health($pdo)], JSON_UNESCAPED_UNICODE); break;
case 'db_init_schema': ensure_infra_schema($pdo); echo json_encode(['ok'=>true,'message'=>'schéma vérifié / initialisé'], JSON_UNESCAPED_UNICODE); break;
case 'browse_db_paths': echo json_encode(['ok'=>true]+browse_paths(isset($payload['path'])?(string)$payload['path']:null), JSON_UNESCAPED_UNICODE); break;
case 'download_db': download_db_file($dbPath?:default_db_path()); break;
case 'list_namespaces': echo json_encode(['ok'=>true,'items'=>list_namespaces($pdo)], JSON_UNESCAPED_UNICODE); break;
case 'list_sensitive': echo json_encode(['ok'=>true,'items'=>list_sensitive($pdo, as_string($payload,'namespace'))], JSON_UNESCAPED_UNICODE); break;
case 'upsert_sensitive': upsert_sensitive($pdo, as_string($payload,'namespace'), as_string($payload,'key'), as_string($payload,'value')); echo json_encode(['ok'=>true], JSON_UNESCAPED_UNICODE); break;
case 'delete_sensitive': echo json_encode(['ok'=>true,'deleted'=>delete_sensitive($pdo, as_string($payload,'namespace'), as_string($payload,'key'))], JSON_UNESCAPED_UNICODE); break;
case 'list_tables': echo json_encode(['ok'=>true,'items'=>list_tables($pdo)], JSON_UNESCAPED_UNICODE); break;
case 'get_table_rows': echo json_encode(['ok'=>true]+get_table_rows($pdo, as_string($payload,'table'), (int)($payload['limit']??100), (int)($payload['offset']??0)), JSON_UNESCAPED_UNICODE); break;
case 'list_npm_instances': echo json_encode(['ok'=>true,'items'=>$pdo->query("SELECT name, base_url, login, password, password_secret_key FROM npm_instances ORDER BY name")->fetchAll()], JSON_UNESCAPED_UNICODE); break;
case 'save_npm_instance': $stmt=$pdo->prepare("INSERT INTO npm_instances(name,base_url,login,password,password_secret_key) VALUES(:name,:base_url,:login,:password,:password_secret_key) ON CONFLICT(name) DO UPDATE SET base_url=excluded.base_url,login=excluded.login,password=excluded.password,password_secret_key=excluded.password_secret_key"); $stmt->execute([':name'=>as_string($payload,'name'),':base_url'=>as_string($payload,'base_url'),':login'=>as_string($payload,'login'),':password'=>$payload['password']??null,':password_secret_key'=>$payload['password_secret_key']??null]); echo json_encode(['ok'=>true], JSON_UNESCAPED_UNICODE); break;
case 'delete_npm_instance': $stmt=$pdo->prepare("DELETE FROM npm_instances WHERE name=:name"); $stmt->execute([':name'=>as_string($payload,'name')]); echo json_encode(['ok'=>true,'deleted'=>$stmt->rowCount()>0], JSON_UNESCAPED_UNICODE); break;
case 'list_npm_services': echo json_encode(['ok'=>true,'items'=>$pdo->query("SELECT domain, instance_name, forward_host, forward_port, scheme FROM npm_services ORDER BY domain")->fetchAll()], JSON_UNESCAPED_UNICODE); break;
case 'save_npm_service': $stmt=$pdo->prepare("INSERT INTO npm_services(domain,instance_name,forward_host,forward_port,scheme) VALUES(:domain,:instance_name,:forward_host,:forward_port,:scheme) ON CONFLICT(domain) DO UPDATE SET instance_name=excluded.instance_name,forward_host=excluded.forward_host,forward_port=excluded.forward_port,scheme=excluded.scheme"); $stmt->execute([':domain'=>as_string($payload,'domain'),':instance_name'=>as_string($payload,'instance_name'),':forward_host'=>as_string($payload,'forward_host'),':forward_port'=>(int)($payload['forward_port']??80),':scheme'=>(string)($payload['scheme']??'http')]); echo json_encode(['ok'=>true], JSON_UNESCAPED_UNICODE); break;
case 'delete_npm_service': $stmt=$pdo->prepare("DELETE FROM npm_services WHERE domain=:domain"); $stmt->execute([':domain'=>as_string($payload,'domain')]); echo json_encode(['ok'=>true,'deleted'=>$stmt->rowCount()>0], JSON_UNESCAPED_UNICODE); break;
case 'list_proxmox_targets': echo json_encode(['ok'=>true,'items'=>$pdo->query("SELECT name, ip, api_path, login, password, password_secret_key, node FROM proxmox_targets ORDER BY name")->fetchAll()], JSON_UNESCAPED_UNICODE); break;
case 'save_proxmox_target': $stmt=$pdo->prepare("INSERT INTO proxmox_targets(name,ip,api_path,login,password,password_secret_key,node) VALUES(:name,:ip,:api_path,:login,:password,:password_secret_key,:node) ON CONFLICT(name) DO UPDATE SET ip=excluded.ip,api_path=excluded.api_path,login=excluded.login,password=excluded.password,password_secret_key=excluded.password_secret_key,node=excluded.node"); $stmt->execute([':name'=>as_string($payload,'name'),':ip'=>as_string($payload,'ip'),':api_path'=>(string)($payload['api_path']??'/api2/json'),':login'=>as_string($payload,'login'),':password'=>$payload['password']??null,':password_secret_key'=>$payload['password_secret_key']??null,':node'=>as_string($payload,'node')]); echo json_encode(['ok'=>true], JSON_UNESCAPED_UNICODE); break;
case 'delete_proxmox_target': $stmt=$pdo->prepare("DELETE FROM proxmox_targets WHERE name=:name"); $stmt->execute([':name'=>as_string($payload,'name')]); echo json_encode(['ok'=>true,'deleted'=>$stmt->rowCount()>0], JSON_UNESCAPED_UNICODE); break;
case 'list_ct_services': echo json_encode(['ok'=>true,'items'=>$pdo->query("SELECT name, target_name, ctid, path FROM ct_services ORDER BY name")->fetchAll()], JSON_UNESCAPED_UNICODE); break;
case 'save_ct_service': $stmt=$pdo->prepare("INSERT INTO ct_services(name,target_name,ctid,path) VALUES(:name,:target_name,:ctid,:path) ON CONFLICT(name) DO UPDATE SET target_name=excluded.target_name,ctid=excluded.ctid,path=excluded.path"); $stmt->execute([':name'=>as_string($payload,'name'),':target_name'=>as_string($payload,'target_name'),':ctid'=>(int)($payload['ctid']??0),':path'=>as_string($payload,'path')]); echo json_encode(['ok'=>true], JSON_UNESCAPED_UNICODE); break;
case 'delete_ct_service': $stmt=$pdo->prepare("DELETE FROM ct_services WHERE name=:name"); $stmt->execute([':name'=>as_string($payload,'name')]); echo json_encode(['ok'=>true,'deleted'=>$stmt->rowCount()>0], JSON_UNESCAPED_UNICODE); break;
case 'list_python_tools': echo json_encode(['ok'=>true,'items'=>list_python_tools()], JSON_UNESCAPED_UNICODE); break;
case 'list_python_files': echo json_encode(['ok'=>true,'items'=>list_python_files()], JSON_UNESCAPED_UNICODE); break;
default: fail('action inconnue: '.$action,404);
}
